
name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint Code base
    runs-on: windows-latest

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v3

      - name: Super-Linter
        uses: github/super-linter@v4.9.5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
